name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 174.138.55.42
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Clone or update repository
          if [ -d "/root/102102" ]; then
            cd /root/102102
            git pull origin main
          else
            git clone https://github.com/${{ github.repository }}.git /root/102102
            cd /root/102102
          fi
          
          # Make scripts executable
          chmod +x deploy_from_github.sh
          chmod +x main_startup.py
          
          # Run deployment
          ./deploy_from_github.sh